"""Generated by llmpl_to_python MVP"""
import sys

def compute_total(base, offset):
    sum_value = (base + offset)
    if (sum_value < 0):
        print('Warning: sum is negative')
    return sum_value

def main(argv):
    greeting = 'Hello'
    audience = 'LLMPL MVP'
    greeting = (str(greeting) + str(', '))
    print((str(greeting) + str(audience)))
    base = 2
    total = compute_total(base, 3)
    print((str('Computed total: ') + str(total)))
    if (total > 3):
        print('Total is greater than three')
    else:
        print('Total is not greater than three')
    flag = True
    if (flag and (total == 5)):
        print('Flag enabled and total is five')
    return total

if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
